[package]
name = "fsvfs"
version = "0.1.0"
edition = "2024"
authors = ["Dasaav"]
license = "MIT OR Apache-2.0"

[dependencies]
base64 = "0.22.1"
clap = { version = "4.6.1", features = ["derive"] }
color-eyre = "0.6.5"
fxhash = "0.2.1"
indexmap = "2.14.0"
malachite = { version = "0.9.1", default-features = false, features = [
    "malachite-nz",
    "naturals_and_integers",
    "std",
] }
memmap2 = "0.9.10"
rkyv = { version = "0.8.16", optional = true }
smallvec = { version = "1.15.1", features = [
    "const_generics",
    "union",
    "const_new",
] }
thiserror = "2.0.18"
tracing = "0.1.44"
zerocopy = { version = "0.8.48", features = ["derive", "std"] }

[target.'cfg(unix)'.dependencies]
fuser = { version = "0.17.0", default-features = false }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.2", features = ["Win32_Storage_FileSystem"] }
winfsp = { version = "0.12.4", default-features = false, features = [
    "handle-util",
    "windows-62",
] }
winfsp-sys = "0.12.1"

[target.'cfg(windows)'.build-dependencies]
winfsp = { version = "0.12.4", default-features = false, features = [
    "build",
    "delayload",
] }

[features]
default = []

[dev-dependencies]
steamlocate = "2.1.0"
xxhash-rust = { version = "0.8.15", features = ["xxh3"] }

[profile.test.package.malachite]
opt-level = 3

[profile.test.package.malachite-nz]
opt-level = 3

[profile.test.package.xxhash-rust]
opt-level = 3
