[package]
name = "fsvfs-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre.workspace = true
futures-util = { workspace = true, features = ["io"] }
rfd = "0.17.2"
# https://github.com/slint-ui/slint/pull/11341
slint = { version = "1.17.0", git = "https://github.com/slint-ui/slint.git", rev = "d38b2d6bfffa309f6d5c8ea66cb2126ace52b264" }

[build-dependencies]
slint-build = { version = "1.17.0", git = "https://github.com/slint-ui/slint.git", rev = "d38b2d6bfffa309f6d5c8ea66cb2126ace52b264" }
