[package]
name = "fsvfs-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
async-fs = "2.2.0"
async-io = "2.6.0"
blocking = "1.6.2"
eyre.workspace = true
futures-util = { workspace = true, features = [
    "async-await",
    "async-await-macro",
] }
normpath.workspace = true
rfd = { version = "0.17.2", features = ["file-handle-inner"] }
serde = { version = "1.0.228", features = ["derive", "rc"] }
serde_json = "1.0.150"
# https://github.com/slint-ui/slint/pull/11341
slint = { version = "1.17.0", git = "https://github.com/slint-ui/slint.git", rev = "d38b2d6bfffa309f6d5c8ea66cb2126ace52b264", default-features = false, features = [
    "std",
    "compat-1-2",
    "accessibility",
    "backend-winit",
    "renderer-software",
] }
steamlocate.workspace = true
xxhash-rust.workspace = true

[target.'cfg(windows)'.dependencies]
papaya = "0.2.4"
tempfile = { version = "3.27.0", default-features = false }
windows = { workspace = true, features = [
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_System_JobObjects",
] }

[build-dependencies]
slint-build = { version = "1.17.0", git = "https://github.com/slint-ui/slint.git", rev = "d38b2d6bfffa309f6d5c8ea66cb2126ace52b264" }

[target.'cfg(windows)'.build-dependencies]
embed-manifest.workspace = true
