#! /bin/bash

cargo run --release -- dvdbnd  -k dist/dvdbnd/Key -d dist/dvdbnd/Hash -m ../eldenring \
    "$HOME/.local/share/Steam/steamapps/common/ELDEN RING/Game/Data0.bhd" \
    "$HOME/.local/share/Steam/steamapps/common/ELDEN RING/Game/Data1.bhd" \
    "$HOME/.local/share/Steam/steamapps/common/ELDEN RING/Game/Data2.bhd" \
    "$HOME/.local/share/Steam/steamapps/common/ELDEN RING/Game/Data3.bhd" \
    "$HOME/.local/share/Steam/steamapps/common/ELDEN RING/Game/DLC.bhd"   \
    "$HOME/.local/share/Steam/steamapps/common/ELDEN RING/Game/sd/sd.bhd" \
    "$HOME/.local/share/Steam/steamapps/common/ELDEN RING/Game/sd/sd_dlc02.bhd"
