import {
    Button,
    CheckBox,
    ComboBox,
    LineEdit,
    ListView,
} from "std-widgets.slint";

import { AboutWindow } from "about.slint";
import { BrowsePath } from "browse.slint";
import { VerticalBorderLayout } from "layout.slint";

struct GameDirs {
    dirs: [string],
    active-index: int,
}

struct BhdCheck {
    name: string,
    parent-dir: string,
    checked: bool,
}

export component AppWindow inherits Window {
    title: "fsvfs GUI";

    preferred-width: 720px;
    preferred-height: 540px;

    in-out property keys-path <=> keys-browse.path;
    in-out property dict-path <=> dict-browse.path;
    in-out property cache-path <=> cache-browse.path;
    in-out property use-cache <=> cache-use-check.checked;

    in-out property <GameDirs> game-dirs;
    in-out property current-game-dir <=> game-dir-browse-combo.current-value;

    in-out property <[BhdCheck]> bhds;

    in-out property mount-point <=> mount-browse.path;
    in-out property mount-enabled <=> mount-button.enabled;

    in-out property game-name <=> game-edit.text;

    callback menu-opened();
    callback menu-saved();

    callback keys-browsed <=> keys-browse.browsed;
    callback dict-browsed <=> dict-browse.browsed;
    callback cache-browsed <=> cache-browse.browsed;

    callback cache-cleared <=> cache-clear-button.clicked;

    callback game-dir-selected();
    callback game-dir-browsed <=> game-dir-browse-button.clicked;

    callback bhd-checked(int);

    callback mount-browsed <=> mount-browse.browsed;
    callback mounted <=> mount-button.clicked;

    private property <bool> about-open;

    MenuBar {
        Menu {
            title: "File";

            MenuItem {
                title: "Open configuration";
                shortcut: @keys(Control+O);
                activated => menu-opened();
            }

            MenuItem {
                title: "Save configuration";
                shortcut: @keys(Control+S);
                activated => menu-saved();
            }
        }

        Menu {
            title: "Help";

            menu-about := MenuItem {
                title: "About";
                activated => {
                    about-open = true;
                }
            }
        }
    }

    VerticalBorderLayout {
        alignment: stretch;
        border-padding: 10px;
        border-spacing: 8px;
        padding: 20px;
        spacing: 8px;

        keys-browse := BrowsePath {
            name: "Keys";
            placeholder-path: "(Default)";
        }

        dict-browse := BrowsePath {
            name: "Dictionary";
            placeholder-path: "(Default)";
        }

        cache-browse := BrowsePath {
            name: "Cache";
            placeholder-path: "(Default)";

            HorizontalLayout {
                alignment: end;
                padding-top: 1px;
                padding-left: 6px;
                padding-right: 8px;
                padding-bottom: 6px;
                spacing: 4px;

                cache-use-check := CheckBox {
                    text: "Use cache";
                }

                cache-clear-button := Button {
                    text: "Clear cache";
                    height: 21px;
                }
            }
        }

        VerticalBorderLayout {
            VerticalLayout {
                padding: 8px;
                spacing: 8px;

                Text {
                    text: "📂     Select game directory:";
                    font-size: 9.5pt;
                    font-weight: FontWeight.thin;
                }

                GridLayout {
                    spacing: 4px;

                    game-dir-browse-combo := ComboBox {
                        height: 24px;
                        model <=> game-dirs.dirs;
                        current-index <=> game-dirs.active-index;
                        selected(_) => game-dir-selected();
                    }

                    game-dir-browse-button := Button {
                        col: 1;
                        text: "Browse";
                        height: 24px;
                    }

                    ListView {
                        row: 1;
                        colspan: 2;

                        for bhd[i] in bhds: CheckBox {
                            height: 20px;
                            text: bhd.name;
                            checked <=> bhd.checked;
                            toggled() => bhd-checked(i);
                        }
                    }
                }
            }
        }

        mount-browse := BrowsePath {
            name: "Mount point";

            HorizontalLayout {
                padding-top: 1px;
                padding-left: 6px;
                padding-right: 8px;
                padding-bottom: 6px;
                spacing: 4px;

                HorizontalLayout {
                    padding-top: 1px;
                    spacing: 6px;
                    height: 22px;

                    Text {
                        text: "🎮     Game";
                        font-size: 9.5pt;
                        font-weight: FontWeight.thin;
                        vertical-alignment: center;
                        min-width: 98px;
                    }

                    game-edit := LineEdit {
                        placeholder-text: "(Autodetect)";
                    }
                }

                mount-button := Button {
                    text: "Mount filesystem";
                    height: 24px;
                }
            }
        }
    }

    if about-open: AboutWindow {
        closed() => {
            about-open = false;
        }
    }
}
