name: Publish release

on:
  release:
    types: created

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    if: github.ref_type == 'tag'
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            exe: fsvfs
            archive: fsvfs-linux-amd64.tar.gz
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            exe: fsvfs.exe
            archive: fsvfs-windows-amd64.zip
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Archive
        run: |
          cp target/${{ matrix.target }}/release/${{ matrix.exe }} ${{ matrix.exe }}
          tar cafv ${{ matrix.archive }} dist ${{ matrix.exe }}

      - name: Configure git
        run: |
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@users.noreply.github.com"

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          name: ${{ github.ref_name }}
          files: ${{ matrix.archive }}

